### ISSUE TITLE
Remove BKB from the mod

### ISSUE THREAD

**Issue by quantuumsnot** [dota2unofficial/12v12#106]
What we have at the moment - add BlackKingBar to supporters with better perks or dota plusers combined with broken heroes means very VERY unbalanced games. Even weakest or balanced heroes become broken AND unkillable with this item

**Comment by GeneralDotV2** [comment]
Black King Bar is one of the most, if not the most crucial item in Dota 2. Removing it really doesn't make much sense to me at all. Doing something about perks seems more reasonable than removing a near required item on most core heroes.

**Comment by darklordabc** [comment]
We arent doing this sorry
