### ISSUE TITLE
Alt-clicking the game time in the top center of the screen does nothing

### ISSUE THREAD

**Issue by hipunk** [dota2unofficial/12v12#11]
Like the title says: When alt-clicking the match time at the top of the screen, usually you should tell your teammates the current game time. However that doesn't work anymore in 12v12.
It's a very minor issue, but worth noting.

**Comment by darklordabc** [comment]
@ark120202 is this a side effect of the custom topbar? And can we fix it?

**Comment by darklordabc** [comment]
It does now
