### ISSUE TITLE
Make kick troll item available for all players and repurpose as a kick troll item

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#111]
It should initiate a kick of an ally player when cast.
Parties of players can only count as 1 vote, and 6 votes are required to kick a player. E.g. if one player in a 5 stack votes to kick another player, than the game assumes the whole party is also voting to kick and they only count as one vote, so they need another 5 votes to kick the player, so in that example, the whole stack plus 5 other players would need to vote to kick.

**Comment by Sheodar** [comment]
So... like troll-vote item?

**Comment by darklordabc** [comment]
Yes, I guess we would remove the kick troll item.

**Comment by darklordabc** [comment]
Done
