### ISSUE TITLE
Don't allow names to take two rows breaking view

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#121]
Should only be allowed one line even if it doesn't show their full name. 
![image](https://user-images.githubusercontent.com/16277198/78594490-c179e580-788b-11ea-8e4b-9e4ae5d283e8.png)

**Comment by Sheodar** [comment]
It's problem for overthrow2, not 12v12. Fixed for overthrow2

**Comment by darklordabc** [comment]
Fixed
