### ISSUE TITLE
Add a confirmation box when somebody changes who they want to pay for

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#128]
At least one player has complained because they purchased benefits with WeChat but it got given to somebody else, they probably made a mistake. A box should come up asking for confirmation when somebody changes the default selection to a different player, requring the user to confirm before it changes the dropbox option.

**Comment by darklordabc** [comment]
I dont think you have finished this @fcalife

**Comment by fcalife** [comment]
My bad, could you remind me what was missing?

**Comment by darklordabc** [comment]
Remeber our discussion where I said that if people hit no on the confirm box it should keep the selection to default (their player), right now it still changes the selection. Only by clicking yes on the confirm box should it be possible to change who you are paying for. Also we still have that dropbox issue for players that disconnect.

**Comment by fcalife** [comment]
alright

**Comment by darklordabc** [comment]
Added
