### ISSUE TITLE
Perks should be balanced

### ISSUE THREAD

**Issue by adminnz** [dota2unofficial/12v12#148]
At the moment if a team has even just 1 player with perks, it creates a huge advantage (e.g. +20% spell amp, +25% magic resistance).
The game should balance out the perks, so that on each team there are the same level & number of perks.
For example, if Radiant have 3 players with tier 2 perks and 1 with tier 2 perks. Then if Dire do not have any perks, it 3 random players on Dire should get tier 2 perks and 1 random player should get tier 2 perks.

Otherwise the game is almost guaranteed to be a stomp with no real chance for the other team to win.

**Comment by GeneralDotV2** [comment]
For every 1 person with perks on a team, the opposite team gets an equal amount of perks of the same level already. It has been this way for months now.

**Comment by vkirilyuk** [comment]
https://github.com/dota2unofficial/12v12/blob/master/game/scripts/vscripts/common/patreons_game_perk/patreon_game_perk.lua

`local correctPerk = perksTierPatreon[newModifierName] and perksTierPatreon[newModifierName] <= patreon.level`

Bullshit. There is nothing in the code that indicates that.

**Comment by adminnz** [comment]
@GeneralDotV2 where exactly in the code is this implemented then? Because I cannot find any indication that such a thing exists.

**Comment by adminnz** [comment]
> For every 1 person with perks on a team, the opposite team gets an equal amount of perks of the same level already. It has been this way for months now.

@GeneralDotV2 are you going to show in the code where it does this? or was that just a lie?

**Comment by vkirilyuk** [comment]
@GeneralDotV2 Hard to lie when code is open, amiright?

**Comment by darklordabc** [comment]
General was honestly mistaken, that is not lying, I suggest you reel it in a bit or I'll ban you, GitHub repo is not a place to call people liars.

**Comment by throwaway-317** [comment]
@darklordabc General was claiming that over and over in the game, despite us failing to find anyone with perks on the opposite team. That was his/her excuse for having 2 other donators in party and ruining games by picking PA / Sniper and having extra 60 agility.

Also, how about some comments on the topic?

**Comment by darklordabc** [comment]
It was a planned feature that never got added, General thought it had been added.

**Comment by adminnz** [comment]
Hi @darklordabc thanks for the reply, is there intention to add this? Because having perks that are so large (20% spell amp, 25% magic resist) make it very unbalanced.

**Comment by adminnz** [comment]
So are you actually going to balance the perks, because at the moment the game is horribly unbalanced?

**Comment by mo-han** [comment]
> 
> 
> So are you actually going to balance the perks, because at the moment the game is horribly unbalanced?

perks superiority => consumer desire => easy money => hail 12v12!
