### ISSUE TITLE
Something is wrong with party/name highlighting

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#152]
there is issue with party system, is not related to our code, its possible for players to be in a 1 man party.
Steps:
1. Player joins a lobby already in a party of 3 people
2. Two other players leave his party
3. That player is solo, but when game starts he must still have a party ID or something

This means that we have to add some kind of check to make sure that there is at least 1 other player with the same partyid, because its possible one player has a unique party ID

![image](https://user-images.githubusercontent.com/16277198/86546673-67b3b500-bf79-11ea-80f8-74255f70c42c.png)

**This is problem in CHC, and Overthrow**

**Comment by SanctusAnimus** [comment]
Should be fixed now
