### ISSUE TITLE
Disable Team Switching after 20 minutes, or make it require vote. 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#154]

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable Team Switching after 20 minutes, or make it require vote. #154](https://trello.com/c/eJXdesNR/232-disable-team-switching-after-20-minutes-or-make-it-require-vote-154)

**Comment by Sheodar** [comment]
Now player cannot change team after 20min +Fixed tracking for top kda/nw players
