### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by junpet** [dota2unofficial/12v12#16]
Can we do something about crashing? It happens when everybody accepts the game. Now I got this nice message thanks for some crashes:
![image](https://user-images.githubusercontent.com/3465278/50425896-09841d00-0880-11e9-86ed-f45b05ce15d2.png)

**Comment by darklordabc** [comment]
I don't know if this problem is reproducible, i can launch fine most of the times. Is it still crashing?

**Comment by GeneralDotV2** [comment]
Sadly this has happened to me 2 times out of about 300 games. I currently have no definitive cause for it.
