### ISSUE TITLE
I made a custom rpg with dota2 map, But sort of hero's talent tree is wrong...

### ISSUE THREAD

**Issue by shenguanjiejie** [dota2unofficial/12v12#168]
Thanks dota2unofficial, I need your help.. I did not find any code for talent in 12v12.

<img width="749" alt="WX20201225-161417@2x" src="https://user-images.githubusercontent.com/9425605/103127583-56986500-46cd-11eb-8b55-0e355b8b78a8.png">
<img width="891" alt="WX20201225-161944@2x" src="https://user-images.githubusercontent.com/9425605/103127587-59935580-46cd-11eb-93db-d69cbf8485d1.png">

**Comment by darklordabc** [comment]
Its probably better to ask on moddota 2 helpdesk.  https://discord.gg/6PhAmYk

**Comment by shenguanjiejie** [comment]
great! Thanks a lot!

**Comment by SanctusAnimus** [comment]
Closing since no longer relevant
