### ISSUE TITLE
Add 'Forfeit' voting option

### ISSUE THREAD

**Issue by quantuumsnot** [dota2unofficial/12v12#17]
Most of the matches end like the following:
1. A couple of "players" left and the match becomes 10v12 or 8v11
2. Even at equal number of players some just start feeding. Usually the result avalanches and after 15 minutes game is in it's seizure state - 72:18 kills ratio
3. Obvious cheating (it's getting harder and harder to detect them tho)

It will be good to have 'Forfeit' voting option so most of us to save our precious sanity and time, it's not cool to agonize 50+ minutes ...

**Comment by darklordabc** [comment]
If players leave, doesnt the game become safe to leave?

**Comment by darklordabc** [comment]
We wont be doing this, soz
