### ISSUE TITLE
Add item/option to reset MMR, can only be used once per month, only by patreons/supporters

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#176]
Add an item to the shop that players can use, that will reset their MMR, only supporters can buy and use this item. There should be a confirmation popup asking if they are sure they want to reset. 

@SanctusAnimus will be required for the server component to make sure they can only do it once every 30 days. 

High-Tier supporters can do it anytime they like, they dont need to wait 30 days.

**Comment by SanctusAnimus** [comment]
It should be present in both 12v12 and OT and have a different cooldown for both of them, right?

**Comment by darklordabc** [comment]
Duplicate
