### ISSUE TITLE
There is no collections button (Only the old cosmetic button)

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#183]
I don't mind using this button, but the text should be updated and the colour changed so players know its diffrent. And there should be a button in the top left to access the collection. Or just a new button on the HUD like we did with CHC.
![image](https://user-images.githubusercontent.com/16277198/104905979-39f30280-59d7-11eb-9892-263755b42ddc.png)

**Comment by Sheodar** [comment]
Fixed: 6abf1fb2afd5016af101a6a80db2cbc1705dd720;
