### ISSUE TITLE
Make Payment Landing Screen for 12v12

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#188]
Do same for Overthrow.

Currently it uses CHC one
![image](https://user-images.githubusercontent.com/16277198/105359323-6e6ef480-5c4b-11eb-9303-aa6f2608dffa.png)

**Comment by natoshi** [comment]
![image](https://user-images.githubusercontent.com/3074666/105645704-0cf59280-5ea4-11eb-9ee0-72cdf0b7db10.png)

**Comment by SanctusAnimus** [comment]
Implemented
