### ISSUE TITLE
Game becomes 11v13 (actually 11vs12) if someone disconnects at the options voting phase

### ISSUE THREAD

**Issue by SanctusAnimus** [dota2unofficial/12v12#198]
![image](https://user-images.githubusercontent.com/43399078/106289401-eb086100-6251-11eb-8ade-de7e2a7aacd9.png)

If you watch the below video, the game isnt actually becoming 13 vs 11, it looks like that in the top bar, what is happening is that a player is not being assigned a hero and is being left stuck in limbo, unable to play the game at all, but for some reason their hero (wisp) is still shown in the top bar making it look like 13 vs 11, when its really 12 vs 11. 
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/GeneralDotV2/ShareX/01-10-2021/issue_with_disconnect_at_vote_stage.mp4

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Game becomes 11v13 if someone disconnects at the options voting phase #198](https://trello.com/c/iTpYzB2N/233-game-becomes-11v13-if-someone-disconnects-at-the-options-voting-phase-198)

**Comment by darklordabc** [comment]
video of how to trigger the bug
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/GeneralDotV2/ShareX/01-10-2021/issue_with_disconnect_at_vote_stage.mp4

**Comment by Sheodar** [comment]
Fixed
