### ISSUE TITLE
Neutral items are dissapear after last update

### ISSUE THREAD

**Issue by iamsiberian** [dota2unofficial/12v12#213]
if I pick up an item and press the "keep" button then the item disappears and becomes unavailable.
if I pick up an item and press the "drop at the base" button, then it becomes available to everyone, but the "take" button is not pressed, then the timer comes to an end and the item becomes available for getting in the "shop->neutral_items" menu.

**Comment by vjt4** [comment]
Adding 4 tiers may have broke [neutral_items_drop_choice.lua](https://github.com/dota2unofficial/12v12/blob/bdd0b8b65442351621b65d492c29a524f3835907/game/scripts/vscripts/neutral_items_drop_choice.lua)
Although, changing the item transfer system may be part of the issue. Trying to look through the neutral item choices logic. RN

**Comment by iamsiberian** [comment]
Fixed in https://github.com/dota2unofficial/12v12/commit/5affc651afaf6e723066fcbe801569ed5350302b
