### ISSUE TITLE
Make possible to ban Rapier and Aegis

### ISSUE THREAD

**Issue by quantuumsnot** [dota2unofficial/12v12#22]
Too many games against cheaters ended in some wacko buying Rapier or part of enemy team also with maphacks to wait near Roshan. Just disable Rapier and Aegis, even not spawning Roshan but instead making there an ancient creeps or directly wipe this area without Roshan's pit

**Comment by darklordabc** [comment]
Yeah I'm not going to disable aegis that's an important part of the game. Nor am I going to disable rapier, the potential for giving rapier to enemy team has always existed, I'm not going to break that trend here.

**Comment by quantuumsnot** [comment]
"Make possible" means add an option for players who WANT to, not breaking the game. In fact the trend here (in almost all mods and in each VALVE updates) is breaking the game balance allowing overpowered situations to arise. In the gaming history this led to players starts cheating or quitting during game and generally stop playing the game almost completely
