### ISSUE TITLE
Bug with buying recipes for boot of travel

### ISSUE THREAD

**Issue by iamsiberian** [dota2unofficial/12v12#220]
1) I have 'boots of speed' and the number of teleports is more than 1
2) I buy any level of 'recipe for boots of travel'

result: the number of teleports becomes 1

**Comment by Snoresville** [comment]
That is an intended dota mechanic mind you.
Extra teleport scrolls are sold until you have one. If you don't have a teleport scroll, dota gives you one for free.

**Comment by iamsiberian** [comment]
Yes, indeed.
It seems to me that this mechanic is very strange - I buy teleport scrolls, which are sold for 50% of the original price (until 1 remains) upon purchase 'boots of travel'.

**Comment by Snoresville** [comment]
In any case, this is not a bug. Thanks for participating.
