### ISSUE TITLE
Swap/Move players between teams possible?

### ISSUE THREAD

**Issue by quantuumsnot** [dota2unofficial/12v12#23]
In some WC3 mods there was possible to swap or move players between teams when the following conditions are met:

1. Host or game master changed player teams due to ingame request or imbalances in forces
2. Two or more players left from one of the teams and manually/automatically one or more from the stronger team are moved to the weaker team

If this is possible it will be very good for the game balance (playing with -2 whole game never been ok)

**Comment by win98se** [comment]
You can refer to #7.

**Comment by darklordabc** [comment]
Duplicate of #7
