### ISSUE TITLE
Add feature to prevent players from dropping other players' items

### ISSUE THREAD

**Issue by Bodi-sama** [dota2unofficial/12v12#27]
Hey, there have been games where a troll would drop other peoples items around the map that go missing. Is there anyway you can implement some feature to prevent this?

**Comment by darklordabc** [comment]
We just added a feature to let  25 dollar tier patrons kick ally players from games. Later we will try to add more general systems everyone can use

**Comment by Bodi-sama** [comment]
Sounds like a plan! If you do decide to add a general feature for everyone to combat this, I suggest there be a "Vote" option to avoid any type of abuse.

**Comment by riri323** [comment]
Thank you Bodi and Devs for doing this. This will really improve the gaming experience. also, pls do consider the vote option to kick out trolls. thank you.

**Comment by darklordabc** [comment]
Added
