### ISSUE TITLE
courier misusage for vision

### ISSUE THREAD

**Issue by Luz** [dota2unofficial/12v12#30]
It looks like a joke for 1st of April, but since the commit is 3 days old I am not sure...
https://github.com/dota2unofficial/12v12/commit/9f5695e3c1eade2c14e3e0cda17acd0cbf09436a
People are misusing courier for vision. Warding and dewarding are more or less useless at the moment.

Even the 10 seconds stun do not help fixing this.
https://github.com/dota2unofficial/12v12/commit/791f72255be56c15eff2c36d4fba807b7ae0dad5

**Comment by darklordabc** [comment]
You mean they just use the courier to skout and don't care if it dies?

**Comment by Luz** [comment]
Yes, or even worse: They use the courier to scout and it does not die at all, if they click fast enough.
