### ISSUE TITLE
minimap is sometimes black background

### ISSUE THREAD

**Issue by riri323** [dota2unofficial/12v12#33]
minimap is about 25% of the time just a dark map with the heroes moving around and we cant see the terrain background. its difficult to see which areas we have vision or not

**Comment by darklordabc** [comment]
Is this on the normal dota map or the other terrains?

**Comment by riri323** [comment]
on normal map,,,my friends also have this issue not just me.

**Comment by darklordabc** [comment]
Does it go black after updates?

**Comment by riri323** [comment]
no, this as been ongoing for a few days now,,,maybe more than a week...ill upload a pic when it happens again

**Comment by riri323** [comment]
https://imgur.com/HN1RlwH here it is

**Comment by darklordabc** [comment]
Did this just happen?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by riri323** [comment]
maybe about 2 weeks now or so...i just reported now because it doesn't happen sometimes.

**Comment by hipunk** [comment]
It happened on non-default terrains for me too and when I said so in all chat, people agreed.

Now everybody plays default terrain tho :D

**Comment by darklordabc** [comment]
This is fixed?

**Comment by darklordabc** [comment]
Doesnt seem to be an issue
