### ISSUE TITLE
Mark as Troll Item

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#34]
Make a new item that players can use to mark a player as a troll, can only be cast on allies. If a player gets more marks certain restrictions will apply to them.

3 Marks - Cannot buy wards, gems, tomes or divine rapiers
6 Marks - Cannot use courier 
7 Marks - 200% Respawn Rate
8 Marks - 250% Respawn Rate
9 Marks - 300% Respawn Rate
10 Marks - 350% Respawn Rate

High tier patrons can use the item unlimited times against any ally.

**Comment by reighnman** [comment]
1. money grab
2. would essentially be instant trolling since that players slot would be occupied, a troll with high marks would simply just need to be in the game (also not kickable via item)
3. just having a vote kick would solve the problem (plus the player deficit gold bonus)

**Comment by darklordabc** [comment]
Not sure what number 2 means, how would it be instant trolling

**Comment by reighnman** [comment]
Wouldnt that be the equiv of afking at fountain?

**Comment by darklordabc** [comment]
If a player wants to afk, kicking them won't fix that

**Comment by reighnman** [comment]
If there are bonuses for player deficit it does

**Comment by darklordabc** [comment]
Outdated not going with anymore
