### ISSUE TITLE
we need to ban more

### ISSUE THREAD

**Issue by wuxinmao2008** [dota2unofficial/12v12#36]
I have played the dota 12V12 for more than hundred times, but i feel more and more unconfortable. As you know , some one played the game for fun , but some one only want to win , which makes the game more and more boring. You can find this hero in every game , such as AA,  zues,  Mercurial，DR，SIL，  Furion and so on. 
I write this above, only to ask you for a faver that can you update the role so that everyone could ban a hero he don't like.  I think current number of ban here which is two is not enough.

**Comment by darklordabc** [comment]
Unfortuntely, we can't modify the bans at the start of the match unless we completly rewrite the hero selection code (currently it uses default code) so I'm going to close this issue for now because we wont be fixing it anytime soon
