### ISSUE TITLE
Show players who left

### ISSUE THREAD

**Issue by riri323** [dota2unofficial/12v12#40]
When the players leave the game, they are removed from the topbar but can we have a way of knowing which heroes have actually left the game. maybe in the scoreboard there can be a status symbol that this hero has left. in 11 vs 11 games its not easy to know who has left or not.

**Comment by darklordabc** [comment]
@Shesmuu could you add some indicator to the player's names in the scoreboards so players can manually check who is disconnected, perhaps a symbol next to their name or their name being a different color.

**Comment by darklordabc** [comment]
This should be for Overthrow too

**Comment by darklordabc** [comment]
Added
