### ISSUE TITLE
Anti-Feeding Detection

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#54]
I had a little idea for how to detect feeding, it's convoluted but it's difficult to distinguish between bad players and feeders so there are a few conditions that have to happen before this anti-feeding triggers. 

There will be a debuff that players can gain if the system detects they are feeding, the debuff will do a couple of things. The debuff lasts for 10 minutes. **The feeder debuff will:**
- Deny the hero if they would die, this prevents feeding.
- Increase the hero's respawn time by 2.5 minutes (this is a punishment, otherwise the denying feature by itself could be considered as a positive)
- Increase in duration by 1 minute if the hero dies while having it (So if they keep feeding it stays on forever)
- ~~Not decrease the duration while the hero is dead.~~

**The conditions to trigger this debuff when a player feeds are as follows:**
- The player must have the worst Kill Death ratio on the team (This is calculated by Kills - Deaths)
- Their KD ratio must be < or equal to - 5
- They must have 3 "Died-Quickly-Tokens*"

*Died-Quickly-Tokens are gained when a player dies within 1.5 minutes of spawning. A counter will go away after 5 minutes (only counts down when the player is alive). Players cannot recieve Died-Quickly-Tokens if they die within this range of Fountain:
![image](https://user-images.githubusercontent.com/16277198/65389514-6f172280-dd9a-11e9-8683-b1e4f369c401.png)

When the debuff ends, the Died-Quickly-Tokens should be set to zero. 

We should also add an item that high-level Patrons can use to cast manually on enemy or allies. The rules for this should be that the targeted hero has the KD condition and worst KD on their team.

**Comment by fcalife** [comment]
Only change I'd propose is making the range for the tokens smaller (about the size of the allied base).

**Comment by darklordabc** [comment]
Implemented
