### ISSUE TITLE
Cannot choose hero

### ISSUE THREAD

**Issue by junpet** [dota2unofficial/12v12#67]
I don't know what happened, but I couldn't choose any hero. I clicked on multiple heroes, but nothing happened. The hero chose sound played, but the hero was not chosen. Time ran out, and now I'm without hero. Can't disconnect, because I got penalty, can't play, because I don't have a hero. I'm curious if I got penalty for being afk...

I remember once I ran out of time Dota randomed me a hero. This would be a good temporary solution. 

[Printscreen](https://i.ibb.co/FzBRh1n/image.png)

**Comment by GeneralDotV2** [comment]
That's a sure sign that the host of that lobby used the "kick from lobby team" option while you were in the lobby.

**Comment by darklordabc** [comment]
This isnt something we can fix, its a valve issue.
