### ISSUE TITLE
Ranger drow attack speed aura needs balance 

### ISSUE THREAD

**Issue by 752346856** [dota2unofficial/12v12#69]
Ranger drow attack speed aura needs balance

I know the hero data of 12vs12 is the same as the normal mode.

But in 12vs12, this skill is too strong.

Increase the attack speed of ranged heroes by 200 in the later stage. It's still free.  
 ᖛ ̫ ᖛ

**Comment by GeneralDotV2** [comment]
It can even be as high as 402 with 6 Ethereal Blades. I'll have to agree that Drow late game even without going all Ethereal Blade is very hard to go against if the Drow team has a majority of ranged heroes. Maybe doing something with the agility as ranged attack speed bonus could be nerfed in some way.

**Comment by darklordabc** [comment]
Drow rangers win rates are pretty low, we wont be nerfing here, at least not yet.
https://pastebin.com/dwek8Eyx
