### ISSUE TITLE
Please auto kick players who intentionally feed and lose numerous divine rapiers

### ISSUE THREAD

**Issue by Bogdanov89** [dota2unofficial/12v12#78]
Really simple, some players join 12v12 with the only intention of:
- constantly feeding as soon as they spawn
- buying wards then placing around fountain (wasting ward charges)
- intentionally giving multiple divine rapiers to the enemy team (runs into enemy fountain/base after buying rapier)
Even one such player completely ruins the game for other 23 players.
Please find a way to automatically kick (permanent disconnect) such players.

**Comment by darklordabc** [comment]
Do these players get the anti-feeder debuff?

**Comment by Bogdanov89** [comment]
I dont really know.
The guy who was doing this on our team had regular respawn time.
He would respawn, waste wards at the fountain, farm jungle for rapier then suicide into enemy base.
He did that i think 4 times.
40 minutes of constant insults and feeding, giving enemies rapier....

**Comment by darklordabc** [comment]
Hmm, we could add a restriction to buying rapiers. Perhaps a kda ratio requirement or needing a high networth to be able to purchase it.

**Comment by darklordabc** [comment]
This is my proposal to mitigate trolls feeding couriers. As for warding, I don't have a proposal yet for that one.

**Comment by darklordabc** [comment]
Have added anti-troll features to combat this
