### ISSUE TITLE
Requirements to Buy Divine Rapier (Anti-Trolling)

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#79]
New Requirements to buy Divine Rapier, to try to prevent trolls from buying it and feeding it. 

- [ ] Players must have a net worth of items 20k or higher, prevents players from commiting all their resources into just buying divine rapiers, they need to have at least other items. Divine rapiers do not count towards the 20k networth limit.

- [ ] For the first divine rapier the player buys, they must have a KD score 5 or higher. KD score is determined by their kills minus their deaths. For any more rapiers after there first, they must have KD score higher than 10. The amount of rapiers they have bought should be counted, it should not depend on whether they have one in their possession or not. 

- [ ] It may be necessary to change the divine rapier item so that it requires a recipe to craft. This recipe could explain the conditions for the item and also prevent players from making it by accident.

**Comment by Bogdanov89** [comment]
Sounds nice thank you.
Any measures to prevent trolling/griefing/teamkilling are very welcome.

**Comment by darklordabc** [comment]
Done
