### ISSUE TITLE
Do you actually ban people who abuse Kick?

### ISSUE THREAD

**Issue by adminnz** [dota2unofficial/12v12#87]
I'm starting to think you do not ban people who abuse the kick function (that you have behind a pay wall).
Guess your just as corrupt as china, gotta keep the people who pay you money, but fuck everyone else.

**Comment by darklordabc** [comment]
We have taken the privilege away from one person so far.

**Comment by adminnz** [comment]
So in match id: 5136354811 are you going to remove the privilege from the person who kicked me for no reason.
It is really great that people who are kicked, can't even join another game and are forced to wait 1 hour before they are able.
It is also really great who you crash the game with no warning at all.

**Comment by dimmskii** [comment]
How about you remove the adware and donations entirely? Now that you put it on GitHub, you have no excuses.

People will "support you" by keeping the code up to date. As opposed to buying you coffee money while buying themselves privileges to crash peoples' clients and block them from completely unrelated gamemodes for 60 minutes at a time.

**Comment by quantuumsnot** [comment]
> How about you remove the adware and donations entirely? Now that you put it on GitHub, you have no excuses.
> 
> People will "support you" by keeping the code up to date. As opposed to buying you coffee whilst buying themselves privileges to crash peoples' clients and block them from completely unrelated gamemodes for 60 minutes at a time.
> 
> This gamemode is seriously going against Valve's ToS. I will be writing them a letter shortly.

Since Dec 2019 I noticed the same so I'm also going to write an e-mail about the mod breaking Valve's ToS.  There's no excuse to ban users from joining any of `Custom games`
Also have the feeling about that the mod is also used as а cheat tool playground for those who make'n'sell those ...
