### ISSUE TITLE
Players are able to purchase multiple tomes within a very short period of time

### ISSUE THREAD

**Issue by GeneralDotV2** [dota2unofficial/12v12#91]
As you can see from this image, this spectre was able to buy 3 tomes by the 12 minute mark.
https://dotv2.com/ShareX/01-07-2020/chrome_12-17PM.jpg

**Comment by darklordabc** [comment]
Is this still a problem?

**Comment by GeneralDotV2** [comment]
This is no longer an issue. Sorry I just noticed your reply.
