### ISSUE TITLE
Please activate my tier .

### ISSUE THREAD

**Issue by lancerace** [dota2unofficial/12v12#96]
https://steamcommunity.com/profiles/76561198082243632/

**Comment by darklordabc** [comment]
You now have the benefits, thanks for the support!

**Comment by Vnzen** [comment]
I don't remember how many days I didn't play, but now when I play, I find that I lost the identity of sponsorship，Please activate my tier too
@darklordabc 
https://steamcommunity.com/profiles/76561198319353651/

**Comment by Vnzen** [comment]
![img](https://www.vnnznn.cn/downloads/test.png)

**Comment by Vnzen** [comment]
![upgrade](https://www.vnnznn.cn/downloads/base.jpg) ![base](https://www.vnnznn.cn/downloads/upgrade.jpg)
